import Foundation
import Testing
@testable import SwiftServeSite
import SwiftServeCapability

@Suite struct SiteGeneratorTests {

    private func makeSite(basePath: String = "") -> Site {
        let taxonomy = Taxonomy(domain: "audio", capabilities: [
            .init(id: "audio.session-management", label: "Audio session management", aliases: ["avaudiosession"]),
            .init(id: "audio.playback", label: "Audio playback"),
        ])
        let guardAnchor = EvidenceAnchor(
            kind: .guard, symbol: "AudioSessionEngineObserver",
            file: "Sources/LiveKit/Audio/AudioSessionEngineObserver.swift", line: 24,
            condition: "os(iOS) || os(visionOS) || os(tvOS)")
        let record = CapabilityRecord(
            package: RecordPackage(canonicalURL: "https://github.com/livekit/client-sdk-swift",
                                   name: "LiveKit", aliases: [], version: "2.15.1",
                                   commit: "7f3af148", surfaceDigest: "fnv1a64:0"),
            capability: CapabilityRef(id: "audio.session-management", label: "Audio session management"),
            platforms: [
                "iOS": PlatformClaim(status: .supported, confidence: 0.9, evidence: [guardAnchor]),
                "macOS": PlatformClaim(status: .unsupported, confidence: 0.85, evidence: [guardAnchor]),
            ],
            labeledBy: "test", labeledAt: "2026-07-02T00:00:00Z")
        let dataset = CapabilityDataset(taxonomy: taxonomy, records: [record])
        return Site(model: SiteModel(dataset: dataset), basePath: basePath)
    }

    @Test func planCoversPagesApiAndLlmsTxt() throws {
        let paths = try SiteGenerator.plan(site: makeSite()).map(\.path)
        for expected in ["index.html", "menu/index.html", "about/index.html", "404.html",
                         "can/audio.session-management/index.html", "can/audio.playback/index.html",
                         "package/client-sdk-swift/index.html",
                         "api/index.json", "api/taxonomy.json", "api/search-index.json",
                         "api/packages/index.json", "api/packages/client-sdk-swift.json",
                         "api/capabilities/audio.session-management.json",
                         "api/schemas/capability-record-v1.json", "llms.txt"] {
            #expect(paths.contains(expected), "missing \(expected)")
        }
        // No capability API file for a capability with zero records.
        #expect(!paths.contains("api/capabilities/audio.playback.json"))
    }

    @Test func capabilityPageCarriesTheReceipt() throws {
        let outputs = try SiteGenerator.plan(site: makeSite())
        let page = String(decoding: outputs.first { $0.path == "can/audio.session-management/index.html" }!.bytes,
                          as: UTF8.self)
        // The verdict permalink pins tag + file + line — the whole trust story.
        #expect(page.contains("https://github.com/livekit/client-sdk-swift/blob/2.15.1/Sources/LiveKit/Audio/AudioSessionEngineObserver.swift#L24"))
        #expect(page.contains("#if os(iOS) || os(visionOS) || os(tvOS)"))
        #expect(page.contains("as of 2.15.1"))
        #expect(page.contains("cell-low"))          // macOS renders as proven-unsupported
        #expect(page.contains("generated by SwiftServeSiteGen"))
    }

    @Test func generationIsDeterministic() throws {
        let a = try SiteGenerator.plan(site: makeSite())
        let b = try SiteGenerator.plan(site: makeSite())
        #expect(a == b)
    }

    @Test func basePathPrefixesEveryAbsoluteHref() throws {
        let outputs = try SiteGenerator.plan(site: makeSite(basePath: "/swiftserve"))
        let home = String(decoding: outputs.first { $0.path == "index.html" }!.bytes, as: UTF8.self)
        #expect(home.contains("href=\"/swiftserve/styles.css\""))
        #expect(home.contains("href=\"/swiftserve/menu/\""))
        #expect(!home.contains("href=\"/styles.css\""))
    }

    @Test func searchIndexIsCompactAndComplete() throws {
        let outputs = try SiteGenerator.plan(site: makeSite())
        let data = outputs.first { $0.path == "api/search-index.json" }!.bytes
        let index = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        let capabilities = index["capabilities"] as! [[String: Any]]
        #expect(capabilities.count == 2)
        let session = capabilities.first { $0["id"] as! String == "audio.session-management" }!
        #expect(session["aliases"] as! [String] == ["avaudiosession"])
        let p = session["p"] as! [String: Int]
        #expect(p["iOS"] == 1)
        #expect(p["macOS"] == 0)
    }
}
