import Foundation
import SwiftServeCapability

/// The hand-written layout shell every generated page shares. Templates are
/// Swift string interpolation — no engine, no framework, matching the house
/// rule that `Public/` stays hand-authored-quality vanilla HTML/CSS/JS.
public struct Site {
    public let model: SiteModel
    /// Prefix for every absolute href ("" for a root deploy; "/swiftserve"
    /// for a GitHub Pages project site).
    public let basePath: String
    /// Optional build stamp (e.g. "2 Jul 2026"). Omitted by default so
    /// regeneration is byte-identical — determinism beats decoration.
    public let stamp: String?
    /// The public origin used in copy-paste embeds (badges, curl examples).
    public let origin: String
    /// Content hash of styles.css + site.js, appended as ?v= to their URLs so
    /// a changed asset is refetched instead of served from a stale cache.
    /// Content-derived, so regeneration stays byte-identical.
    public let assetVersion: String?
    /// The project's own source repository — linked from the header mark,
    /// the footer, and every contribute prompt.
    public let repoURL = "https://github.com/nanoncore/swiftserve"

    public init(model: SiteModel, basePath: String = "", stamp: String? = nil,
                origin: String = "https://swiftserve.dev", assetVersion: String? = nil) {
        self.model = model
        self.basePath = basePath.hasSuffix("/") ? String(basePath.dropLast()) : basePath
        self.stamp = stamp
        self.origin = origin.hasSuffix("/") ? String(origin.dropLast()) : origin
        self.assetVersion = assetVersion
    }

    /// Absolute URL for embeds that leave the site (README badges, curl).
    public func absolute(_ path: String) -> String { origin + basePath + path }

    /// The category pill bar — quick switching between capability groups.
    /// Pills link to the menu's group anchors; `current` highlights one.
    public func categoryPills(current: String? = nil) -> String {
        let pills = model.categories.map { category -> String in
            let isCurrent = category.prefix == current
            return """
            <a class="chip\(isCurrent ? " chip-current" : "")" href="\(href("/menu/#\(category.prefix)"))"\(isCurrent ? " aria-current=\"true\"" : "")>\(Html.escape(category.label))<span class="chip-count">\(category.capabilityCount)</span></a>
            """
        }.joined(separator: "\n          ")
        return """
        <nav class="pill-bar" aria-label="Categories">
          \(pills)
        </nav>
        """
    }

    public func href(_ path: String) -> String { basePath + path }

    private var assetQuery: String { assetVersion.map { "?v=\($0)" } ?? "" }

    /// A cache-busted script tag for a page-specific asset (same ?v= scheme
    /// as the shared styles/site.js pair).
    public func script(_ path: String) -> String {
        "<script src=\"\(href(path))\(assetQuery)\" defer></script>"
    }

    // MARK: - Page shell

    public func page(title: String, description: String, path: String,
                     wide: Bool = false, extraHead: String = "", main: String) -> String {
        let fullTitle = title.isEmpty ? "SwiftServe" : "\(title) — SwiftServe"
        return """
        <!doctype html>
        <!-- generated by SwiftServeSiteGen — edit Sources/SwiftServeSite, not this file -->
        <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>\(Html.escape(fullTitle))</title>
          <meta name="description" content="\(Html.escape(description))" />
          <link rel="icon" href="\(href("/swiftee/swiftee-idle.png"))" />
          <link rel="stylesheet" href="\(href("/styles.css"))\(assetQuery)" />
          <script src="\(href("/site.js"))\(assetQuery)" defer></script>
          \(extraHead)</head>
        <body class="site\(wide ? " wide" : "")">
          \(header(currentPath: path))
          <main id="main">
        \(main)
          </main>
          \(footer())
        </body>
        </html>
        """
    }

    private func header(currentPath: String) -> String {
        func navLink(_ label: String, _ path: String, cls: String? = nil) -> String {
            let current = currentPath == path ? " aria-current=\"page\"" : ""
            let classAttr = cls.map { " class=\"\($0)\"" } ?? ""
            return "<a\(classAttr) href=\"\(href(path))\"\(current)>\(label)</a>"
        }
        return """
        <header class="top-nav">
            <a class="wordmark" href="\(href("/"))">🍦 <strong>SwiftServe</strong></a>
            <nav aria-label="Primary">
              \(navLink("Menu", "/menu/"))
              \(navLink("Scoop", "/scoop/"))
              \(navLink("Agents", "/agents/"))
              \(navLink("About", "/about/"))
              <form class="nav-search" action="\(href("/"))" role="search" data-search hidden>
                <input type="search" name="q" placeholder="press / to search" aria-label="Search capabilities" />
              </form>
            </nav>
            <a class="nav-github" href="\(repoURL)" rel="noopener" aria-label="SwiftServe on GitHub" title="View source on GitHub">\(Self.githubMark)</a>
            \(navLink("Get", "/get/", cls: "nav-cta"))
          </header>
        """
    }

    private func footer() -> String {
        let counts = "\(model.capabilities.filter { !$0.rows.isEmpty }.count) capabilities × \(model.packages.count) packages · \(model.recordCount) records · data v\(model.dataset.datasetVersion)"
        let served = stamp.map { "Served fresh · rebuilt \($0) · " } ?? "Served fresh · "
        return """
        <footer class="site-footer">
            <p>\(served)\(counts)</p>
            <p>Every verdict links to the exact source line that decides it. <a href="\(href("/about/"))">How it works</a> · <a href="\(repoURL)" rel="noopener">Source on GitHub</a></p>
            <p>Made refreshingly cool from Paris, France</p>
          </footer>
        """
    }

    /// GitHub's mark (octicons mark-github), inlined so the icon needs no
    /// extra asset fetch and inherits the nav's currentColor.
    static let githubMark = """
    <svg viewBox="0 0 16 16" width="20" height="20" aria-hidden="true"><path fill="currentColor" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8z"/></svg>
    """
}

public enum Html {
    public static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    /// An attribute-safe id fragment (capability ids contain dots).
    public static func idSafe(_ s: String) -> String {
        s.map { $0.isLetter || $0.isNumber ? String($0) : "-" }.joined()
    }
}

/// Shared verdict-cell vocabulary: glyph + class per status, used by both the
/// capability table and the package matrix so the language never drifts.
public enum VerdictCell {
    public static func glyph(_ status: ClaimStatus) -> String {
        switch status {
        case .supported: "✓"
        case .conditional: "◐"
        case .unsupported: "✕"
        case .unknown: "?"
        }
    }

    public static func cssClass(_ status: ClaimStatus) -> String {
        switch status {
        case .supported: "cell-good"
        case .conditional: "cell-warn"
        case .unsupported: "cell-low"
        case .unknown: "cell-unknown"
        }
    }

    public static func word(_ status: ClaimStatus) -> String {
        switch status {
        case .supported: "serves it"
        case .conditional: "with conditions"
        case .unsupported: "not served here"
        case .unknown: "not verified yet"
        }
    }

    /// The evidence receipt: a cell is a <details> so the proof works with
    /// zero JavaScript; site.js upgrades presentation, never meaning.
    public static func cell(claim: PlatformClaim?, platform: Platform, record: CapabilityRecord,
                            site: Site) -> String {
        guard let claim else {
            return """
            <td class="cell-unknown"><span class="cell-glyph" title="not verified yet">?</span></td>
            """
        }
        let status = claim.status
        let confidenceClass = claim.confidence < 0.75 && status != .unknown ? " conf-soft" : ""
        guard !claim.evidence.isEmpty else {
            return """
            <td class="\(cssClass(status))\(confidenceClass)"><span class="cell-glyph" title="\(word(status))">\(glyph(status))</span></td>
            """
        }
        let items = claim.evidence.prefix(3).map { anchor -> String in
            var lines: [String] = []
            if let symbol = anchor.symbol {
                lines.append("<code>\(Html.escape(symbol))</code>")
            }
            if let condition = anchor.condition {
                lines.append("<code class=\"evidence-guard\">#if \(Html.escape(condition))</code>")
            }
            if record.package.firstParty {
                // SDK symbols have no repo line to link — the receipt is the
                // symbol graph; the outbound link is Apple's documentation.
                if let symbol = anchor.symbol {
                    let path = symbol.split(separator: ".")
                        .map { $0.lowercased() }.joined(separator: "/")
                    let permalink = "\(record.package.canonicalURL)/\(path)"
                    lines.append("<span class=\"evidence-loc\">Apple SDK symbol graph · \(Html.escape(record.package.version))</span>")
                    lines.append("<a class=\"evidence-link\" href=\"\(Html.escape(permalink))\" rel=\"noopener\">View in Apple Docs →</a>")
                }
            } else if let file = anchor.file, let line = anchor.line {
                let target = anchor.package ?? record.package.canonicalURL
                let tag = record.package.version
                let permalink = "\(target)/blob/\(tag)/\(file)#L\(line)"
                lines.append("<span class=\"evidence-loc\">\(Html.escape(file)):\(line)</span>")
                lines.append("<a class=\"evidence-link\" href=\"\(Html.escape(permalink))\" rel=\"noopener\">View the line on GitHub →</a>")
            }
            if let note = anchor.note {
                lines.append("<span class=\"evidence-note\">\(Html.escape(note))</span>")
            }
            return "<li>\(lines.joined(separator: "<br />"))</li>"
        }
        let confidence = String(format: "%.2f", claim.confidence)
        return """
        <td class="\(cssClass(status))\(confidenceClass)">
          <details class="evidence">
            <summary aria-label="\(word(status)) on \(PlatformDisplay.label(platform)), confidence \(confidence)"><span class="cell-glyph">\(glyph(status))</span></summary>
            <div class="evidence-pop">
              <p class="evidence-verdict">\(word(status)) · confidence \(confidence) · as of \(Html.escape(record.package.version))</p>
              <ul>\(items.joined())</ul>
            </div>
          </details>
        </td>
        """
    }
}
