#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
build_dir=${1:-"$root/.build/release"}

case "$(uname -s)" in
  Darwin) resource_suffix=bundle ;;
  Linux) resource_suffix=resources ;;
  *) echo "staged release resources: skipped (unsupported host)"; exit 0 ;;
esac

cli_resource="$build_dir/SwiftServe_SwiftServeCLI.$resource_suffix"
evidence_resource="$build_dir/SwiftServe_SwiftServeEvidence.$resource_suffix"
test -x "$build_dir/swiftserve"
test -d "$cli_resource"
test -d "$evidence_resource"

scratch=$(mktemp -d)
stage="$scratch/stage"
homebrew="$scratch/homebrew"
hidden="$scratch/build-resources"
mkdir -p "$stage" "$homebrew/bin" "$hidden"
cp "$build_dir/swiftserve" "$stage/swiftserve"
cp -R "$cli_resource" "$stage/"
cp -R "$evidence_resource" "$stage/"
cp "$build_dir/swiftserve" "$homebrew/bin/swiftserve"
cp -R "$cli_resource" "$homebrew/bin/"
cp -R "$evidence_resource" "$homebrew/bin/"

restore() {
  if [ -d "$hidden/SwiftServe_SwiftServeCLI.$resource_suffix" ]; then
    mv "$hidden/SwiftServe_SwiftServeCLI.$resource_suffix" "$cli_resource"
  fi
  if [ -d "$hidden/SwiftServe_SwiftServeEvidence.$resource_suffix" ]; then
    mv "$hidden/SwiftServe_SwiftServeEvidence.$resource_suffix" "$evidence_resource"
  fi
  rm -rf "$scratch"
}
trap restore EXIT HUP INT TERM

# Hide the hard-coded build-tree fallbacks generated by SwiftPM. The staged
# binary can now succeed only by finding both resources beside itself.
mv "$cli_resource" "$hidden/"
mv "$evidence_resource" "$hidden/"

"$stage/swiftserve" capability-check livekit \
  --capability audio.session-management --platform macos --json >/dev/null
"$stage/swiftserve" scan-source \
  "$root/Sources/SwiftServeCore/Models/Pin.swift" --json >/dev/null
"$homebrew/bin/swiftserve" capability-check livekit \
  --capability audio.session-management --platform macos --json >/dev/null

echo "staged release resources: archive, installer, and Homebrew layouts loaded outside .build"
